/**
 * Colorini levels — each bottle is an array of colors from bottom to top.
 * Empty bottles are []. Capacity is 4 unless overridden.
 */
window.COLORINI_LEVELS = [
  {
    name: "Primi passi",
    capacity: 4,
    bottles: [
      ["red", "blue", "red", "blue"],
      ["blue", "red", "blue", "red"],
      [],
    ],
  },
  {
    name: "Tre colori",
    capacity: 4,
    bottles: [
      ["green", "yellow", "green", "yellow"],
      ["yellow", "sky", "yellow", "green"],
      ["sky", "green", "sky", "sky"],
      [],
      [],
    ],
  },
  {
    name: "Incrocio",
    capacity: 4,
    bottles: [
      ["orange", "pink", "orange", "teal"],
      ["pink", "teal", "pink", "orange"],
      ["teal", "orange", "teal", "pink"],
      [],
      [],
    ],
  },
  {
    name: "Arcobaleno soft",
    capacity: 4,
    bottles: [
      ["red", "blue", "lime", "amber"],
      ["blue", "amber", "red", "lime"],
      ["lime", "red", "amber", "blue"],
      ["amber", "lime", "blue", "red"],
      [],
      [],
    ],
  },
  {
    name: "Torri miste",
    capacity: 4,
    bottles: [
      ["indigo", "rose", "indigo", "green"],
      ["rose", "green", "rose", "indigo"],
      ["green", "indigo", "green", "rose"],
      ["sky", "amber", "sky", "amber"],
      ["amber", "sky", "amber", "sky"],
      [],
      [],
    ],
  },
  {
    name: "Doppio strato",
    capacity: 4,
    bottles: [
      ["teal", "teal", "orange", "pink"],
      ["orange", "pink", "teal", "orange"],
      ["pink", "orange", "pink", "teal"],
      ["blue", "yellow", "blue", "yellow"],
      ["yellow", "blue", "yellow", "blue"],
      [],
      [],
    ],
  },
  {
    name: "Labirinto",
    capacity: 4,
    bottles: [
      ["red", "sky", "lime", "red"],
      ["sky", "lime", "red", "sky"],
      ["lime", "red", "sky", "lime"],
      ["amber", "pink", "amber", "pink"],
      ["pink", "amber", "pink", "amber"],
      ["indigo", "green", "indigo", "green"],
      ["green", "indigo", "green", "indigo"],
      [],
      [],
    ],
  },
  {
    name: "Cascata",
    capacity: 4,
    bottles: [
      ["rose", "blue", "yellow", "teal"],
      ["blue", "yellow", "teal", "rose"],
      ["yellow", "teal", "rose", "blue"],
      ["teal", "rose", "blue", "yellow"],
      ["lime", "orange", "lime", "orange"],
      ["orange", "lime", "orange", "lime"],
      [],
      [],
    ],
  },
  {
    name: "Prisma",
    capacity: 4,
    bottles: [
      ["red", "orange", "yellow", "lime"],
      ["orange", "yellow", "lime", "sky"],
      ["yellow", "lime", "sky", "blue"],
      ["lime", "sky", "blue", "indigo"],
      ["sky", "blue", "indigo", "pink"],
      ["blue", "indigo", "pink", "red"],
      ["indigo", "pink", "red", "orange"],
      ["pink", "red", "orange", "yellow"],
      [],
      [],
    ],
  },
  {
    name: "Maestro",
    capacity: 4,
    bottles: [
      ["red", "teal", "amber", "pink"],
      ["teal", "amber", "pink", "indigo"],
      ["amber", "pink", "indigo", "lime"],
      ["pink", "indigo", "lime", "sky"],
      ["indigo", "lime", "sky", "orange"],
      ["lime", "sky", "orange", "red"],
      ["sky", "orange", "red", "teal"],
      ["orange", "red", "teal", "amber"],
      [],
      [],
    ],
  },
  {
    name: "Bonus — Nido",
    capacity: 4,
    bottles: [
      ["green", "green", "rose", "sky"],
      ["rose", "sky", "green", "rose"],
      ["sky", "green", "sky", "rose"],
      ["yellow", "blue", "yellow", "blue"],
      ["blue", "yellow", "blue", "yellow"],
      ["orange", "indigo", "orange", "indigo"],
      ["indigo", "orange", "indigo", "orange"],
      [],
      [],
    ],
  },
  {
    name: "Bonus — Tempesta",
    capacity: 4,
    bottles: [
      ["blue", "indigo", "pink", "amber"],
      ["indigo", "pink", "amber", "lime"],
      ["pink", "amber", "lime", "teal"],
      ["amber", "lime", "teal", "rose"],
      ["lime", "teal", "rose", "sky"],
      ["teal", "rose", "sky", "orange"],
      ["rose", "sky", "orange", "blue"],
      ["sky", "orange", "blue", "indigo"],
      ["orange", "blue", "indigo", "pink"],
      [],
      [],
    ],
  },
];
