/**
 * Colorini levels — each bottle is an array of colors from bottom to top.
 * Empty bottles are []. Capacity is 4 unless overridden.
 */
window.COLORINI_LEVELS = [
  {
    name: "Primi passi",
    capacity: 4,
    bottles: [
      ["red", "blue", "red", "blue"],
      ["blue", "red", "blue", "red"],
      [],
    ],
  },
  {
    name: "Tre colori",
    capacity: 4,
    bottles: [
      ["green", "yellow", "green", "yellow"],
      ["yellow", "cyan", "yellow", "green"],
      ["cyan", "green", "cyan", "cyan"],
      [],
      [],
    ],
  },
  {
    name: "Incrocio",
    capacity: 4,
    bottles: [
      ["orange", "purple", "orange", "cream"],
      ["purple", "cream", "purple", "orange"],
      ["cream", "orange", "cream", "purple"],
      [],
      [],
    ],
  },
  {
    name: "Arcobaleno soft",
    capacity: 4,
    bottles: [
      ["red", "blue", "coral", "brown"],
      ["blue", "brown", "red", "coral"],
      ["coral", "red", "brown", "blue"],
      ["brown", "coral", "blue", "red"],
      [],
      [],
    ],
  },
  {
    name: "Torri miste",
    capacity: 4,
    bottles: [
      ["navy", "magenta", "navy", "green"],
      ["magenta", "green", "magenta", "navy"],
      ["green", "navy", "green", "magenta"],
      ["cyan", "brown", "cyan", "brown"],
      ["brown", "cyan", "brown", "cyan"],
      [],
      [],
    ],
  },
  {
    name: "Doppio strato",
    capacity: 4,
    bottles: [
      ["cream", "cream", "orange", "purple"],
      ["orange", "purple", "cream", "orange"],
      ["purple", "orange", "purple", "cream"],
      ["blue", "yellow", "blue", "yellow"],
      ["yellow", "blue", "yellow", "blue"],
      [],
      [],
    ],
  },
  {
    name: "Labirinto",
    capacity: 4,
    bottles: [
      ["red", "cyan", "coral", "red"],
      ["cyan", "coral", "red", "cyan"],
      ["coral", "red", "cyan", "coral"],
      ["brown", "purple", "brown", "purple"],
      ["purple", "brown", "purple", "brown"],
      ["navy", "green", "navy", "green"],
      ["green", "navy", "green", "navy"],
      [],
      [],
    ],
  },
  {
    name: "Cascata",
    capacity: 4,
    bottles: [
      ["magenta", "blue", "yellow", "cream"],
      ["blue", "yellow", "cream", "magenta"],
      ["yellow", "cream", "magenta", "blue"],
      ["cream", "magenta", "blue", "yellow"],
      ["coral", "orange", "coral", "orange"],
      ["orange", "coral", "orange", "coral"],
      [],
      [],
    ],
  },
  {
    name: "Prisma",
    capacity: 4,
    bottles: [
      ["red", "orange", "yellow", "coral"],
      ["orange", "yellow", "coral", "cyan"],
      ["yellow", "coral", "cyan", "blue"],
      ["coral", "cyan", "blue", "navy"],
      ["cyan", "blue", "navy", "purple"],
      ["blue", "navy", "purple", "red"],
      ["navy", "purple", "red", "orange"],
      ["purple", "red", "orange", "yellow"],
      [],
      [],
    ],
  },
  {
    name: "Maestro",
    capacity: 4,
    bottles: [
      ["red", "cream", "brown", "purple"],
      ["cream", "brown", "purple", "navy"],
      ["brown", "purple", "navy", "coral"],
      ["purple", "navy", "coral", "cyan"],
      ["navy", "coral", "cyan", "orange"],
      ["coral", "cyan", "orange", "red"],
      ["cyan", "orange", "red", "cream"],
      ["orange", "red", "cream", "brown"],
      [],
      [],
    ],
  },
  {
    name: "Bonus — Nido",
    capacity: 4,
    bottles: [
      ["green", "green", "magenta", "cyan"],
      ["magenta", "cyan", "green", "magenta"],
      ["cyan", "green", "cyan", "magenta"],
      ["yellow", "blue", "yellow", "blue"],
      ["blue", "yellow", "blue", "yellow"],
      ["orange", "navy", "orange", "navy"],
      ["navy", "orange", "navy", "orange"],
      [],
      [],
    ],
  },
  {
    name: "Bonus — Tempesta",
    capacity: 4,
    bottles: [
      ["blue", "navy", "purple", "brown"],
      ["navy", "purple", "brown", "coral"],
      ["purple", "brown", "coral", "cream"],
      ["brown", "coral", "cream", "magenta"],
      ["coral", "cream", "magenta", "cyan"],
      ["cream", "magenta", "cyan", "orange"],
      ["magenta", "cyan", "orange", "blue"],
      ["cyan", "orange", "blue", "navy"],
      ["orange", "blue", "navy", "purple"],
      [],
      [],
    ],
  },
];
